from enum import Enum

class JobStatus(str, Enum):
    CREATED = "CREATED"
    DISCOVERING = "DISCOVERING"
    WAITING_FOR_CAPTCHA = "WAITING_FOR_CAPTCHA"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    FAILED = "FAILED"

class RecordStatus(str, Enum):
    PENDING = "PENDING"
    WAITING_FOR_CAPTCHA = "WAITING_FOR_CAPTCHA"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class ErrorCategory(str, Enum):
    TIMEOUT = "TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    EMPTY_RECORD = "EMPTY_RECORD"
    PORTAL_LAYOUT_CHANGED = "PORTAL_LAYOUT_CHANGED"
    CAPTURE_ERROR = "CAPTURE_ERROR"
    PDF_WRITE_ERROR = "PDF_WRITE_ERROR"
    LOCATION_SELECTION_MISMATCH = "LOCATION_SELECTION_MISMATCH"
    SURVEY_SELECTION_MISMATCH = "SURVEY_SELECTION_MISMATCH"
    UNKNOWN = "UNKNOWN"
